Mrc 1837
mrc-ide/mint pull request #47
Opened 2020-10-21 11:48 UTC by hillalex

2020-10-26 14:09 UTC, hillalex commented on src/app/static/src/app/models/project.ts
> -    setCurrentRegion(url: string) {
Since the state needs to be serialisable, these classes can't have methods. This logic has been moved to the `SetCurrentRegion` mutation.

2020-10-27 17:07 UTC, EmmaLRussell requested changes
This works really nicely. One little bug - navigating back to the project index page, then forward to the region page throws `TypeError: Cannot set property 'currentRegion' of null`

2020-10-27 17:09 UTC, EmmaLRussell commented
Oh, just noticed the build has failed, maybe something was broke in the merge

> This works really nicely. One little bug - navigating back to the project index page, then forward to the region page throws `TypeError: Cannot set property 'currentRegion' of null`

2020-10-27 17:20 UTC, hillalex commented
> Oh, just noticed the build has failed, maybe something was broke in the merge
> 
> > This works really nicely. One little bug - navigating back to the project index page, then forward to the region page throws `TypeError: Cannot set property 'currentRegion' of null`

Ah no, the build failure is cos of a mintr update. Will fix that and look into the bug :+1:

2020-10-28 11:17 UTC, EmmaLRussell approved these changes

2020-10-28 11:17 UTC, merged